config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :agent_verifications, only: [ :index, :update ]
  end
  resources :password_resets, only: [ :new, :create, :edit, :update ]
  resources :account_activations, only: [ :edit ]
  resources :orders
  resources :products

  root 'static_pages#home'
end

app/models/user.rb
class User < ApplicationRecord

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_AGENT_ID_REGEX = /(^(0|[1-9][0-9]*)$|^((0|[1-9][0-9]*)\.)+(0|[1-9][0-9]*)$)/
  VALID_NAME_REGEX = /\A\w+$\z/

  validates :first_name,
    presence: true,
    format: { with: VALID_NAME_REGEX }
  validates :last_name,
    presence: true,
    format: { with: VALID_NAME_REGEX }
  validates :email,
    presence: true,
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  validates :password,
    presence: true,
    length: { minimum: 7 }
  validates :agent_id,
    presence: true,
    length: { minimum: 1 },
    format: { with: VALID_AGENT_ID_REGEX },
    uniqueness: true

  has_many :orders,
    primary_key: :agent_id,
    foreign_key: :agent_id

  attr_accessor :password_reset_token, :remember_me_token, :activation_token

  has_secure_password

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def create_password_reset_digest
    self.password_reset_token = User.new_token
    update_attribute(:password_reset_digest, User.digest(password_reset_token))
    update_attribute(:password_reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def remember
    self.remember_me_token = User.new_token
    update_attribute(:remember_me_token, User.digest(remember_me_token))
  end

  def verify
    update_attribute(:verified_agent, true) && update_attribute(:verified_at, Time.zone.now)
  end

  def forget
    self.remember_me_token = nil
    update_attribute(:remember_me_token, nil)
  end

  def authenticate_token(token_type, token_value)
    digest = send("#{token_type.to_s.remove("_token")}_digest")
    return nil unless digest
    BCrypt::Password.new(digest).is_password?(token_value)
  end

  def send_activation_email
    self.activation_token = User.new_token
    update_attribute(:activation_digest, User.digest(activation_token))
    UserMailer.account_activation(self).deliver_now
  end

  private
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [ :index, :edit, :update, :destroy ]
  before_action :admin_user, only: :destroy
  before_action :correct_user, only: [ :edit, :update ]

  add_breadcrumb "users", :users_path

  def index
    @users = User.all
  end

  def show
    @user = User.find_by id: params[:id]
    add_breadcrumb "#{@user.first_name.downcase}", user_path(@user)
  end

  def new
    @user = User.new
    add_breadcrumb "signup", signup_path
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:success] = "TODO: Sign up done!"
      redirect_to root_url
    elsif
      flash.now[:danger] = "TODO: Opps, something went wrong with your sign up..."
      render :new
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "TODO: update success"
      redirect_to user_path(@user)
    else
      flash.now[:danger] = "TODO: update failed"
      render :new
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash.now[:warning] = "User deleted!"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name,
        :email,
        :agent_id,
        :password, :password_confirmation)
    end

    def correct_user
      @user = User.find_by(id: params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<li>
  <p><strong>email: </strong><%= user.email %></p>
  <p><%= link_to "delete", user_path(user), method: :delete,
    data: { confirm: "Are you sure?" } %></p>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1>Edit</h1>
    <%= form_for @user do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :first_name, "Given name" %>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :last_name, "Family name" %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email, "Email" %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :agent_id, "Agent ID" %>
        <%= f.text_field :agent_id, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password, "Password" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, "Confirm password" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <%= f.submit "Save Changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<table class="table">
  <tr>
    <th>No.</th>
    <th>Name</th>
    <th>Surname</th>
    <th>email</th>
    <th>Agent ID</th>
    <th></th>
    <th></th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= user.agent_id %></td>
      <td><%= link_to "show", user_path(user) %></td>
      <td>
        <% if user.id == current_user.id %>
          <%= link_to "edit", edit_user_path(user) %>
        <% elsif current_user.admin? %>
          <%= link_to "delete", users_path, method: :delete,
            data: { confirm: "Are you sure?" },
            style: "color:red;" %>
        <% else %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1>Sign up</h1>
    <%= form_for @user do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :first_name, "Given name" %>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :last_name, "Family name" %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email, "Email" %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :agent_id, "Agent ID" %>
        <%= f.text_field :agent_id, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password, "Password" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, "Confirm password" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <%= f.submit "Sign up", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Profile") %>
<div class="row">
  <div class="col-md-12">
    <h1>User profile</h1>
    <p>Name: <%= "#{@user.first_name} #{@user.last_name}" %></p>
    <p>Email: <%= @user.email %></p>
    <p>Agent ID: <%= @user.agent_id %></p>
  </div>
</div>