config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :agent_verifications, only: [ :index, :update ]
  end
  resources :password_resets, only: [ :new, :create, :edit, :update ]
  resources :account_activations, only: [ :edit ]
  resources :orders
  resources :products

  root 'static_pages#home'
end

app/models/order.rb
class Order < ApplicationRecord

  NO_REGEX = /\A(0|[1-9][0-9]*)\z/

  belongs_to :user, primary_key: :agent_id, foreign_key: :agent_id
  has_many :sales, primary_key: :no, foreign_key: :order_no

  validates :no,
    presence: true,
    uniqueness: true,
    format: { with: NO_REGEX }

  accepts_nested_attributes_for :sales
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :logged_in_user
  before_action :agent_user
  before_action :admin_user, only: [ :destroy ]
  add_breadcrumb "orders", :orders_path

  def index
    flash[:success] = "TODO: test"
    @orders = Order.where(agent_id: current_user.agent_id) || []
  end

  def show
    @order = Order.find_by(no: params[:id])
    @user = User.find_by(agent_id: @order.agent_id)
    @sales = []
    Sale.where(order_no: @order.no).each do |sale|
      product = Product.find_by(sid: sale.product_sid)
      @sales << [ sale, product ]
    end
    add_breadcrumb @order.no.to_s, order_path(@order)
  end

  def new
    @order = Order.new
    @products = []
    Product.all.each do |product|
      @products << [ "#{product.name} (ID: #{product.sid}, RM #{product.suggested_price})",
        product.sid ]
    end
    add_breadcrumb "new", new_order_path
  end

  def create
    if order_params[:sales_attributes]
      order = current_user.orders.create(no: order_params[:no])
      order_params[:sales_attributes].each do |key, value|
        product = Product.find_by(sid: value[:product_sid])
        sale_price = (value[:sale_price].is_a? Numeric) ? value[:sale_price] :
          product.suggested_price
        sale = Sale.create(order_no: order.no, product_sid: value[:product_sid], sale_price:
          sale_price, amount: value[:amount].to_i)
      end
    else
      order = current_user.orders.build(order_params)
    end
    if order.save
      flash[:success] = "TODO: ok"
      redirect_to orders_url
    else
      flash.now[:danger] = "TODO: error!"
      render :new
    end
  end

  def edit
    @order = Order.find_by(id: params[:id])
    @sales = @order.sales.all
  end

  def update
  end

  def destroy
  end

  private

    def order_params
      params.require(:order).permit(:no, sales_attributes: [ :product_sid, :sale_price, :amount ])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit.html.erb
<% provide(:title, "Order") %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1>Order (edit)</h1>
    <%= form_for @order do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :no, "No." %>
        <%= f.number_field :no, class: "form-control" %>
      </div>
      <%= f.add_nested_fields_link :sales, "Add", class: "btn btn-success", role: "button" %>
      <%= f.submit "Create", class: "btn btn-primary" %>
      <hr>
      <ul class="list-group">
        <%= f.nested_fields_for :sales, wrapper_tag: :li, wrapper_options: { class:
          "list-group-item" } do |sf| %>
          <div class="form-group">
            <%= sf.remove_nested_fields_link "Delete", class: "btn btn-danger", role: "button" %>
          </div>
          <div class="form-group">
            <%= sf.label :product_sid, "Product" %>
            <%= sf.select(:product_sid, options_for_select(@products), {}, class:
              "form-control") %>
          </div>
          <div class="form-group">
            <%= sf.label :amount, "Amount" %>
            <%= sf.number_field :amount, class: "form-control", step: 1, placeholder: "1" %>
          </div>
          <div class="form-group">
            <%= sf.label :sale_price, "Sale price (RM)" %>
            <%= sf.number_field :sale_price, class: "form-control", step: 0.01, placeholder:
              "Custom value (optional)" %>
          </div>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/orders/index.html.erb
<h1>Orders</h1>
<table class="table">
  <tr>
    <th>Order No.</th>
    <th>Agent ID</th>
    <th>Amount Sold</th>
    <th>Total Sales (RM)</th>
  </tr>
  <% @orders.each do |order| %>
    <tr>
      <% user = User.find_by(agent_id: order.agent_id) %>
      <% sales = Sale.where(order_no: order.no) %>
      <td><%= link_to "#" + order.no.to_s, order_path(order) %></td>
      <td><%= link_to user.agent_id, user_path(user) %></td>
      <td><%= sales.count > 0 ? sales.sum(&:amount) : 0 %></td>
      <td>RM <%= sales.count > 0 ? sales.sum(&:sale_price) : 0.00 %></td>
    </tr>
  <% end %>
</table>

app/views/orders/new.html.erb
<% provide(:title, "New | Orders") %>
<%= form_for @order do |f| %>
  <div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title">New Order</h3></div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <%= f.label :no, "No." %>
            <%= f.number_field :no, class: "form-control",
              step: 1, min: 0 %>
          </div>
          <%= f.submit "Create", class: "btn btn-success" %>
          <br>
          <br>
        </div>
        <div class="col-md-8">
          <p>Add order sales info by clicking on the <strong>+</strong> button below. The
            <strong>Sale Price</strong> is optional, the product standard price will be used by
            default.</p>
          <p>
            For custom values, make sure you enter in the <strong>price per product.</strong>
          </p>
        </div>
      </div>
    </div>
    <table class="table">
      <col width="auto">
      <col width="80px">
      <col width="120px">
      <col width="7px">
      <tr>
        <th>Product</th>
        <th>*</th>
        <th>Sale Price (RM)</th>
        <th>
          <%= f.add_nested_fields_link :sales, "+",
            role: "button",
            style: "text-decoration: none;" %>
        </th>
      </tr>
      <%= f.nested_fields_for :sales, wrapper_tag: :tr do |sf| %>
        <td>
          <div class="form-group">
            <%= sf.select(:product_sid, options_for_select(@products), {}, class: "form-control") %>
          </div>
        </td>
        <td>
          <div class="form-group">
            <%= sf.number_field :amount, class: "form-control", placeholder: "1",
              value: 1, min: 1, max: 99, step: 1 %>
          </div>
        </td>
        <td>
          <div class="form-group">
            <%= sf.number_field :sale_price, class: "form-control", placeholder: "Optional",
              step: 0.01, min: 0.01, max: 9999.99 %>
          </div>
        </td>
        <td>
          <%= sf.remove_nested_fields_link "x", role: "button",
            class: "text-danger",
            style: "text-decoration: none;" %>
        </td>
      <% end %>
    </table>
  </div>
<% end %>

app/views/orders/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Order #<%= @order.no %></h1>
    <div class="panel panel-default">
      <div class="panel-body">
        <p>
          <strong>Agent ID: </strong>
          <%= link_to @user.agent_id, user_path(@user) %>
        </p>
        <p>
          <strong>Agent name: </strong>
          <%= link_to "#{@user.first_name} #{@user.last_name}", user_path(@user) %>
        </p>
        <p>
          <strong># of sales: </strong>
          <%= link_to @sales.count, '#' %>
        </p>
        <p>
          <strong>Sales amount: </strong>
          <%= link_to "RM #{@order.sales.sum(&:sale)}", '#' %>
        </p>
      </div>
      <table class="table">
        <tr>
          <th>Product ID</th>
          <th>Product Name</th>
          <th>Suggested Price</th>
          <th>Sale Price</th>
          <th>Price %</th>
        </tr>
        <% @sales.each do |sale| %>
          <tr>
            <% s = sale[0] %>
            <% p = sale[1] %>
            <td><%= link_to p.id, product_path(p) %></td>
            <td><%= link_to p.name, product_path(p) %></td>
            <td><%= link_to "RM #{p.suggested_price}", product_path(p) %></td>
            <td><%= s.sale %></td>
            <td><%= (s.sale / p.suggested_price) * 100 %>%</td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>