config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :agent_verifications, only: [ :index, :update ]
  end
  resources :password_resets, only: [ :new, :create, :edit, :update ]
  resources :account_activations, only: [ :edit ]
  resources :orders
  resources :products

  root 'static_pages#home'
end

app/controllers/agent_verifications_controller.rb
class AgentVerificationsController < ApplicationController

  add_breadcrumb "users", :users_path
  before_action :add_user_breadcrumb, only: [ :index, :edit ]

  def index
    agents_regex = "\\\A" + current_user.agent_id.gsub(".", '\\.') + "\\\.(0|[1-9][0-9]*)\\\Z"
    @unverified_agents = User.where('agent_id ~ ?', agents_regex).where(verified_agent: false)
    add_breadcrumb "pending", user_agent_verifications_path(current_user.id)
  end

  def update
    @agent = User.find_by(id: params[:id])
    if @agent.verify
      flash[:success] = "TODO: ok, verified"
      redirect_to user_agent_verifications_path(current_user)
    else
      flash[:danger] = "TODO: something went wrong with verification"
      redirect_to user_agent_verifications_path(current_user)
    end
  end

  private

    def add_user_breadcrumb
      add_breadcrumb current_user.first_name.downcase, user_path(current_user)
    end

end

app/helpers/agent_verifications_helper.rb
module AgentVerificationsHelper
end

app/views/agent_verifications/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Agents Pending Your Verification</h3>
      </div>
      <div class="panel-body">
        <p>Below are agents waiting for your verification. Click on <span class="text-success">
          verify</span> to confirm that the agent's ID is correct. If any of the agents below is
          not under you, click on <span class="text-danger">delete</span> to deny the agent's
          account.</p>
      </div>
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Surname</th>
          <th>Agent ID?</th>
          <th></th>
          <th></th>
        </tr>
        <% @unverified_agents.each do |u_agent| %>
          <tr>
            <td><%= u_agent.first_name %></td>
            <td><%= u_agent.last_name %></td>
            <td><%= u_agent.agent_id %></td>
            <td>
              <%= link_to "verify", user_agent_verification_path(user_id: current_user.id,
                id: u_agent.id), method: :patch,
                data: { confirm: "Verify #{u_agent.first_name}?" },
                class: "text-success" %>
            </td>
            <td>
              <%= link_to "delete", user_path(u_agent.id), method: :delete,
                data: { confirm: "This will delete #{u_agent.first_name}. Are you sure?" },
                class: "text-danger" %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>