config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :agent_verifications, only: [ :index, :update ]
  end
  resources :password_resets, only: [ :new, :create, :edit, :update ]
  resources :account_activations, only: [ :edit ]
  resources :orders
  resources :products

  root 'static_pages#home'
end

app/views/layouts/_breadcrumbs.html.erb
<body>
  <ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => "" %>
  </ol>
</body>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %> alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
          data-target="#data-target" aria-expanded="false">
          <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
        </button>
        <%= link_to "Mary Jardin", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="data-target">
        <ul class="nav navbar-nav navbar-left">
          <% if logged_in? %>

            <!-- Users dropdown. -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                role="button" aria-haspopup="true" aria-expanded="false">
                Users <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "All", users_path %></li>
                <li>
                  <%= link_to "Agent Verification", user_agent_verifications_path(current_user) %>
                </li>
              </ul>
            </li>

            <!-- Orders dropdown. -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                role="button" aria-haspopup="true" aria-expanded="false">
                Orders <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "New", new_order_path %></li>
                <li><%= link_to "View", orders_path %></li>
              </ul>
            </li>

            <!-- Products dropdown. -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                role="button" aria-haspopup="true" aria-expanded="false">
                Products <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "New", new_product_path %></li>
                <li><%= link_to "View", products_path %></li>
              </ul>
            </li>

          <% else %>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Log out", logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign up", signup_path %></li>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all',
      'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
      'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div id="application-container" class="container">
      <div class="row">
        <div class="col-md-8">
          <%= render 'layouts/breadcrumbs' %>
          <%= yield %>
        </div>
        <div class="col-md-4">
          <%= render 'layouts/flash' %>
        </div>
      </div>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>